### ISSUE TITLE
Make language support Java-compatible

### ISSUE THREAD

**Issue by ramack** [danielwippermann/resol-vbus-java#14]
I suggest to implement a method
SpecificationFile.Language getLanguageForLocale(Locale l);

which does a mapping of java locales to the Language values used in the vbus-java APIs.
I guess SpecificationFile is the best class candidate. In case the locale is not supported by the SpecificationFile the defaul "En" should be returned.

**Comment by danielwippermann** [comment]
Please have a look at the impl proposal in b2df07b57fadf73b294ef6f715034331aae595a3.
