### ISSUE TITLE
mvn repository

### ISSUE THREAD

**Issue by ramack** [danielwippermann/resol-vbus-java#17]
with #6 I requested to have a jar of the library, but this is also not what they want to have in the openhab repo...

Can create a public mvn repository for it? Maybe @fwolter can give some more hints if necessary.

**Comment by danielwippermann** [comment]
Short status update: I have prepared a repo for testing purposes yesterday and plan to use that repo in an example application in the next couple of days.

I'll keep you posted :)

**Comment by danielwippermann** [comment]
Okay, I did a little test and it seemed to work. I included the following to my `pom.xml`:

```xml
<!-- ... -->
  <dependencies>
    <!-- ... -->
    <dependency>
      <groupId>de.resol</groupId>
      <artifactId>vbus</artifactId>
      <version>0.3.0</version>
    </dependency>
  </dependencies>
  <!-- ... -->
  <repositories>
    <!-- ... -->
    <repository>
      <id>resol-vbus</id>
      <url>https://mvn-repository.hackmaniac.de/</url>
    </repository>
  </repositories>
<!-- ... -->
```
 And it worked. Would that solve this issue for you, @ramack?

**Comment by danielwippermann** [comment]
The library has been published to the central Maven repo:

https://repo1.maven.org/maven2/de/resol/vbus/
