### ISSUE TITLE
SensorOutputType

### ISSUE THREAD

**Issue by ramack** [danielwippermann/resol-vbus-java#19]
When I read the SensorOutputTypeX fields in the frame 6651_7E11 transmitted from my MX (2.06 firmware if I am not mistaken) I would expect the sensor type to be transmitted, but I read always 0 - whatever I set as sensor type in the MX, both with PacketFieldValue.getRawValueLong() and getRawValueDouble() is this working properly and I am doing something wrong here or is there a bug in the library or the MX - as the EM doesn't use the information it might be not a problem in real setups but I might want to use it int eh OH binding.

The sensor type in the EM is anyhow irrelevant, right?

**Comment by danielwippermann** [comment]
Yes, it is no longer used since the EM simply transmits the raw resistor values to the controller and the controller itself performs the selected conversion into a temperature value. The SensorOutputType is from a time where the conversion was done in the EM.

**Comment by ramack** [comment]
ok, so in that case I cannot autodetect what type of input is expected from the controller and provide all (of those I want to support) in parallel.
