### ISSUE TITLE
EmDeviceEmulator tx update

### ISSUE THREAD

**Issue by ramack** [danielwippermann/resol-vbus-java#20]
Currently EmDeviceEmulator transmits the new state of the sensors in packetReceived, so the write is somehow delayed.

Is this a vbus-protcol requirement or could it be changed, e.g. by adding a new method: txDataNow() in case the data change should be transmitted as fast as possible (e. g. when using in emulated EM input as switch to react asap).

**Comment by danielwippermann** [comment]
This is a VBus protocol requirement, since the EM is a slave device and may only send on the bus after being asked to do so.

**Comment by ramack** [comment]
ok, thanks for the clarification.
