### ISSUE TITLE
Accumulating TCP connections

### ISSUE THREAD

**Issue by ramack** [danielwippermann/resol-vbus-java#21]
In some situations (I don't yet catch the exact conditions) the resol-vbus-java library seems to accumulate open TCP connections.

In a quick stepping session it looks like TcpConnection.connectInternal() is called while this.socket is still a valid, open socket. Shouldn't that one be closed before (or maybe better after) the new one was opened and set?

I have seen situations where the code in case CONNECTED of runInBackground() the IOException was thrown as
`java.net.SocketTimeoutException: Read timed out` - which might happen in case another device opens a connection the the TCP interface in the DLx or VBUS/LAN-Adapter.

Last but not least, I have the feeling, that there a some "synchronized"s missing in class TcpConnection, as multiple Threads modify the connectionState. - In my case I call connect even from different application threads which might not be wise, but also the backgroundThread started in connect() modifies it together with the application calls.

Maybe the soTimeout of 5000 set in TcpConnection.connectInternal() is too small in some situations?

Also I got
```
java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1043)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:997)
	at de.resol.vbus.Connection.setConnectionState(Connection.java:105)
	at de.resol.vbus.Connection.checkAndSetConnectionState(Connection.java:118)
	at de.resol.vbus.TcpConnection.runInBackground(TcpConnection.java:136)
```
in one situation and I believe, that calling the vbus library only from one thread would not fully fix this - what do you think?

**Comment by danielwippermann** [comment]
Ah, good catches.

Yes, not closing the socket will most certainly lead to a out-of-resources situation.

And the missing `sychronized` in combination with not copying the `listeners` ArrayList before calling the listeners may lead to the CME you encountered.

I have implemented the necessary changes to all three problems in my local working copy already.

Regarding the 5 second socket timeout: I cannot imagine a situation where that should not be enough to be honest.

I'll publish a new JAR once I get the tests running again (current JDK behaves differently on macOS and Linux :( ).

**Comment by danielwippermann** [comment]
I just published version 0.6.0 of the JAR that includes the bug fixes discussed above.

**Comment by ramack** [comment]
Great, thanks. Do you think it makes sense to annotate the 0.6 tag to be a release ingithub? https://github.com/danielwippermann/resol-vbus-java/releases as currently github claims 0.3 to be the latest release...

**Comment by danielwippermann** [comment]
Good idea, done!
