### ISSUE TITLE
simulate a BAS module

### ISSUE THREAD

**Issue by ramack** [danielwippermann/resol-vbus-java#22]
For simulating a BAS module on a emulated EM, we'd need to know the nominal resistor values for the different modes and the set temperature offset. Can you provide those? Or even implement a method like setResistorValueByNrAndBasSettings(tempOffset, mode) in class EmDeviceEmulator?

**Comment by danielwippermann** [comment]
I added the method in commit 7abf3f17d490d50c2dbcd8b4396b5e0ecc52e8b4. Please give it a try!
