### ISSUE TITLE
Update release binaries

### ISSUE THREAD

**Issue by chiefdeputy** [danielwippermann/resol-vbus-java#24]
Hello Daniel,

I'm currently developing a docker image which uses your java lib. I have two questions:

1. Is it possible to update the releases with the current jar? This would reduce my build time in docker, as I don't have to build the jar.
2. Is the jar usable with Java 11 JRE? 1.8 is not shipped with debian anymore... (I need additional apk repos.)

Thank you!

**Comment by danielwippermann** [comment]
Hi chiefdeputy!

Done! :)

https://github.com/danielwippermann/resol-vbus-java/releases/tag/v0.9.0

Best regards,
Daniel

**Comment by chiefdeputy** [comment]
Thanks!
