### ISSUE TITLE
Localization of DeviceNames Missing

### ISSUE THREAD

**Issue by ramack** [danielwippermann/resol-vbus-java#5]
Specification.getSourceDeviceSpec(packet).getName()
always returns the German device name, e.g. "DeltaSol MX [Regler]" insteaf of "DeltaSol MX [Controller]". I guess this is an issue in the VSF and not in the java code, but never the less it is not soo nice any maybe you find a way to fix that. If not; I, as a German, can also live with it, just close this issue with a wontfix tag :-)

**Comment by danielwippermann** [comment]
Version 8 of the VSF should fix most of the German / English localization problems. It is scheduled to be releases in January. I'll keep this issue open until the VSF is updated in this repo.

**Comment by ramack** [comment]
thanks for the update

**Comment by ramack** [comment]
any news about the release of the VSF?

**Comment by danielwippermann** [comment]
Approval of the file took longer than expected but finally passed today. VSF and corresponding tests were updated in f6264bab6b356ed3dda73deddd10d9b2be047c6c.

**Comment by ramack** [comment]
looks great now. Thanks for fixing.
